### ISSUE TITLE
Atom 1.19.2 Linux, Strange Character in Output

### ISSUE THREAD

**Issue by vanboom** [fcoury/atom-rspec#100]
```
Randomized with seed 7598
..

Finished in 0.93096 seconds (files took 0.25511 seconds to load)
2 examples, 0 failures
```
The strange characters have appeared after an upgrade of Atom to 1.19.2

**Comment by layonferreira** [comment]
Hello, @vanboom .
Does this issue, only happens with atom-rspec or it also happens if you run rspec from your terminal?

**Comment by layonferreira** [comment]
Closing this issue due to lack of response.
If this issue persists, please create another issue and provide more information.

**Comment by vanboom** [comment]
Happening now with atom 1.26.1, Linux, rspec 3.4.0,
rspec options:  `--format progress --color`
```
Randomized with seed 24801
...............F............
```
It does not happen when rspec is run from the terminal.
