### ISSUE TITLE
Force colored results, produces [] caractere

### ISSUE THREAD

**Issue by cheesepaulo** [fcoury/atom-rspec#102]
![captura de tela de 2018-09-28 09 27 19](https://user-images.githubusercontent.com/13470825/46214448-d70a6880-c300-11e8-9638-22203763e279.png)

On disable this function:

![captura de tela de 2018-09-28 09 29 03](https://user-images.githubusercontent.com/13470825/46214512-f5706400-c300-11e8-9571-45c2191c7f8c.png)
It's fine, but no colors.

**Comment by cheesepaulo** [comment]
Atom version: 1.31.1

At linux terminal, works fine with colors.

**Comment by vanboom** [comment]
Has anyone solved this?  Trying to debug it and not having any luck yet.

**Comment by vanboom** [comment]
Update:  need to replace the ESC character byte code 0x18.

Around line 42 in text-formatter.coffee
```coffee
 text = text.replace /\x1B/g, ''
```
I will submit a PR asap.

**Comment by vanboom** [comment]
I already had an outstanding PR #86 so it got rolled into that.

**Comment by cheesepaulo** [comment]
thanks @vanboom :+1:
