### ISSUE TITLE
Split pane horizontally

### ISSUE THREAD

**Issue by exalted** [fcoury/atom-rspec#18]
How can you split pane horizontally by default when one is opened automatically?

**Comment by ahmetabdi** [comment]
:+1:

**Comment by ahmetabdi** [comment]
Need this so bad :cactus:  :sob:

**Comment by matugm** [comment]
@ahmetabdi You can resize the panel by draging it with your mouse (in atom 0.200+) if it's taking too much space for you :)

**Comment by oddityoverseer13** [comment]
:+1: 
A hack to get this is to "split down" the pane, then run rspec, then drag the rspec tab into that new pane.

**Comment by lowski** [comment]
+1 for horizontal split

**Comment by ritxi** [comment]
I added this feature, just check PR #87

**Comment by exalted** [comment]
Maybe with recent improvements in Atom this issue is not relevant anymore? Should we close this?

**Comment by dkniffin** [comment]
@exalted What recent improvements?

**Comment by exalted** [comment]
@dkniffin I was thinking of [Drag and Drop Layout Management](http://blog.atom.io/2016/06/06/atom-1-8-and-1-9-beta.html#drag-and-drop-layout-management). Not sure if it's realted though, hence my question. :beers:
