### ISSUE TITLE
rspec command not found after updating to Atom 0.169.0

### ISSUE THREAD

**Issue by felipecsl** [fcoury/atom-rspec#43]
``bash: line 1: rspec: command not found``

**Comment by felipecsl** [comment]
Never mind, it was just me being stupid :)

**Comment by szyablitsky** [comment]
@felipecsl I'm stupid too ) How did you resolve this issue?

**Comment by szyablitsky** [comment]
Resolved.
Forgot to add rbenv to .bashrc
