### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ahmetabdi** [fcoury/atom-rspec#47]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/ahmet/.atom/packages/rspec/lib/rspec.coffee:21:9)
```

**Comment by matugm** [comment]
Should be fine now, thanks for reporting.

**Comment by ahmetabdi** [comment]
:+1:
