### ISSUE TITLE
Package stopped working.

### ISSUE THREAD

**Issue by tombroomfield** [fcoury/atom-rspec#52]
Really love this plugin, very recently though it has completely stopped working. Running my keyboard shortcuts does not do anything, neither running it through the palette. I have tried restarting and updating both Atom and atom-rspec. Any ideas what could be happening?

**Comment by matugm** [comment]
What are your Atom and atom-rspec versions? If you go to 'View -> Developer -> Toggle developer tools' do you see any errors?

**Comment by tombroomfield** [comment]
Hi, thanks for getting back to me.
I am using Atom 0.194.0 at the latest version of atom-rspec.
When I go to initiate the specs, the dev console provides feedback that they seem to have started, and then I get an 'Exit code 1' log back. However, no panes open with the specs. I wish I had more information to give you, I can get screenshots of the console output tomorrow when I am back on my work computer?

Thanks,

**Comment by matugm** [comment]
Sure, that would help. Also check the package settings, we made some changes recently in that department.

**Comment by tombroomfield** [comment]
We are back online! No idea what solved it, simply came back to work today and everything is working as normal. Thanks for the great plugin, pivotal piece in my workflow.
