### ISSUE TITLE
broke my shortcuts to run specs

### ISSUE THREAD

**Issue by betarelease** [fcoury/atom-rspec#58]
I have the latest version and now I am not able to use the shortcuts like Ctrl+Alt+T, Ctrl+Alt+E etc.

**Comment by kianw** [comment]
same

**Comment by jkeck** [comment]
FWIW I added the following to my keymap (`Atom -> Open Your Keymap`) temporarily to get my shortcuts back.

```
'atom-text-editor':
  'ctrl-alt-x': 'rspec:run-for-line'
  'ctrl-alt-t': 'rspec:run'
  'ctrl-alt-r': 'rspec:run-all'
```

There is currently a PR (see #59) about fixing this in the `atom-rspec` package itself to use `-` instead of `+` in the provided keymap.

**Comment by betarelease** [comment]
Thanks @jkeck. That worked for me.

**Comment by matugm** [comment]
Should be fixed on latest version.
