### ISSUE TITLE
Does not active with Atom 0.206.0

### ISSUE THREAD

**Issue by jwhitcraft** [fcoury/atom-rspec#61]
With the latest version of atom this plug does not active out of the box due to using deprecated APIs.

**Comment by matugm** [comment]
You can run Atom with --include-deprecated-apis to deal with that until we have an updated version.

**Comment by jwhitcraft** [comment]
That's what i'm doing, I just wanted to let you know.

**Comment by cliffrowley** [comment]
Hey, `--include-deprecated-apis` doesn't seem to work for me for some reason and the package is still not activated.  Any idea when you might push a release?  Days?  Weeks? ;-)  Thanks!

**Comment by matugm** [comment]
We just published a new version.
