### ISSUE TITLE
Package.activateConfig is deprecated.

### ISSUE THREAD

**Issue by Riddlerrr** [fcoury/atom-rspec#66]
Use a config schema instead. See the configuration section
of https://atom.io/docs/latest/hacking-atom-package-word-count and
https://atom.io/docs/api/latest/Config for more details
```
Package.activateConfig (/opt/atom/resources/app.asar/src/package.js:265:11)
PackageDetailView.activate (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
PackageDetailView.initialize (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:12)
PackageDetailView.View (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
new PackageDetailView (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:38:54)
<unknown> (/opt/atom/resources/app.asar/node_modules/settings-view/lib/settings-view.js:256:22)
```

**Comment by andywenk** [comment]
will this be fixed or do we need yet another fork? ;-)

**Comment by matugm** [comment]
It's not clear to me exactly what needs to be done to get this fixed. Feel free to send a pull request and I will merge it in.

**Comment by andywenk** [comment]
As far as I can see, you need to change this https://github.com/fcoury/atom-rspec/blob/master/lib/rspec.coffee with the new type of config settings. You read how in https://atom.io/docs/api/v1.0.2/Config "Defining settings for your package". A quick google search lead me to this example: https://github.com/AtomLinter/linter-tidy/commit/f66fe5b952cf8972c9b62120984b2f28dcb401a7

Hope that helps

**Comment by fcoury** [comment]
@andywenk would you be able to fork the project, fix the problem and submit a Pull Request?

**Comment by andywenk** [comment]
I can't promise but if I find time I will do so. I have to work myself into creating atom plugins first ;-) (never did create one ...)
