### ISSUE TITLE
Configuration weirdness

### ISSUE THREAD

**Issue by moxley** [fcoury/atom-rspec#8]
There's some weirdness how the configuration gets written and used. To recreate:

1. Edit your config.cson. Remove anything related to 'rspec' or 'atom-rspec'. Save.
2. Go into the settings UI for Atom Rspec. Change the command to "foo".
3. Go back to config.cson. It now has configuration settings for both "rspec" and "atom-rspec", and they're different from each other.
4. Run a spec. It runs whatever was in the "rspec" configuration, not what was in "atom-rspec".
5. Changing the setting in the settings UI only changes the configuration for "atom-rspec", but it doesn't get picked up by the package.

Is this a bug in Atom? Or atom-rspec? I can't figure it out.

**Comment by matugm** [comment]
Is this still a problem for anyone?

**Comment by siannopollo** [comment]
I just tested on version 0.1.9 and this is still a problem. I also have to manually change the `atom-rspec[command]` value in order to use zeus with rspec. The current code is still saving the config value to `rspec[command]`, but trying to read from `atom-rspec[command]`.

**Comment by matugm** [comment]
@siannopollo Thanks. Any chance you could test master? I think it should be fixed now.

**Comment by siannopollo** [comment]
I just updated to the latest (0.2.0) and the runner is now saving the command under `rspec[command]`, and using the same. I'd say this is working.
