### ISSUE TITLE
Command setting isn't in the UI anymore

### ISSUE THREAD

**Issue by jamesgecko** [fcoury/atom-rspec#85]
The "Command" setting doesn't appear on the package's settings page as illustrated in the readme.

![](https://camo.githubusercontent.com/47d6b33a1e4cf364d8c7262d1dc1616b38a27437/687474703a2f2f662e636c2e6c792f6974656d732f326b314330453065316c325a336d316c336531522f53657474696e67732532302d2532302d55736572732d66636f7572792d50726f6a656374732d63726d5f626c6973732e6a7067)

![screen shot 2016-01-21 at 12 13 44 pm](https://cloud.githubusercontent.com/assets/44252/12488209/760521a6-c038-11e5-8788-49c5bb70158d.png)

**Comment by born4new** [comment]
Status on this?

**Comment by jamesgecko** [comment]
The "Command" GUI setting is back. 😃
